baseURL = 'https://pentest-bi0s.github.io/'
languageCode = 'en-us'
title = 'bi0s Pentest Blog'
theme = 'PaperMod'

# Enable emoji support
enableEmoji = true

# Enable search functionality
[params.homeInfoParams]
  Title = "Welcome to Our bi0s Pentest Blog"
  Content = "Sharing insights, techniques and knowledge about cybersecurity and penetration testing"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  disableSpecial1stPost = false
  
  [params.profileMode]
    enabled = false

  [params.assets]
    disableHLJS = true
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    
  # Social icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/pentest-bi0s"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/bi0s.pentest"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:teambi0spentest@gmail.com"

# Menu items
[menu]
  [[menu.main]]
    identifier = "main-site"
    name = "Back to Main Website"
    url = "https://pentest.bi0s.in"
    weight = 5
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 35
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

